export {default as Routes} from './Routes'
export {default as HomePage} from './HomePage'
export {default as SynthBoard} from './SynthBoard'
export {default as WhiteKey} from './WhiteKey'
export {default as BlackKey} from './BlackKey'
